// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodosApplication.DAL;

namespace TodosApplication.Migrations
{
    [DbContext(typeof(TodoContext))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("TodosApplication.Model.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deadline = new DateTime(2021, 5, 10, 12, 8, 44, 571, DateTimeKind.Local).AddTicks(4740),
                            Details = "Csak egy teszt",
                            Name = "Teszt",
                            Order = 1,
                            TypeId = 1
                        });
                });

            modelBuilder.Entity("TodosApplication.Model.TodoType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TodoTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Függőben",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Folyamatban",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kész",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Elhalasztva",
                            Order = 4
                        });
                });

            modelBuilder.Entity("TodosApplication.Model.Todo", b =>
                {
                    b.HasOne("TodosApplication.Model.TodoType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
